name: lint and test

on:
  - push
  - pull_request

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup UV
        uses: astral-sh/setup-uv@v2
        with:
          python-version: '3.10'
          enable-cache: true

      - name: Install dependencies
        run: uv pip install --system -e ".[dev]"

      - name: Run linting
        run: python -m flake8 gendiff

      - name: Run tests with coverage
        run: python -m pytest --cov=gendiff --cov-report=xml tests/

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.9.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=gendiff
            -Dsonar.tests=tests
            -Dsonar.python.version=3.10
