name: lint and test

on:
  - push
  - pull_request

jobs:
  test:
    name: Testing and SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup UV
        uses: astral-sh/setup-uv@v2
        with:
          python-version: '3.10'
          enable-cache: true

      - name: Create virtual environment
        run: uv venv

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          uv pip install -e . pytest pytest-cov coverage

      - name: Run tests with coverage
        run: |
          source .venv/bin/activate
          python -m pytest --cov=gendiff --cov-report=xml tests/

      - name: SonarCloud Scan (updated action)
        uses: SonarSource/sonarcloud-github-action@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=gendiff
            -Dsonar.tests=tests
            -Dsonar.python.version=3.10
