name: lint

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Setup poetry
        run: poetry install

      - run: make lint