name: lint

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup poetry
      - run: curl -sSL https://install.python-poetry.org | python3 -
      
      - run: make lint