name: CI with SonarCloud

on:
  - push
  - pull_request

jobs:
  test:
    name: Test and Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -e . pytest pytest-cov coverage

      - name: Run tests and generate coverage
        run: |
          python -m coverage run --source=. --omit="tests/*,__pycache__/*" -m pytest tests/
          python -m coverage xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=dimondimasik
            -Dsonar.projectKey=DimonDimasik_python-project-50
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=.
            -Dsonar.tests=tests
            -Dsonar.python.version=3.10
