name: CI with SonarCloud

on:
  - push
  - pull_request

jobs:
  test:
    name: Test and Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup UV
        uses: astral-sh/setup-uv@v2
        with:
          python-version: '3.10'
          enable-cache: true

      - name: Install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e . pytest pytest-cov coverage

      - name: Run tests with coverage
        run: |
          source .venv/bin/activate
          cd $GITHUB_WORKSPACE
          python -m coverage run --source=gendiff -m pytest tests/
          python -m coverage xml

      - name: Fix coverage paths
        run: |
          echo "Current paths in coverage.xml:"
          grep "filename=" coverage.xml | head -5
          echo "Fixing paths..."
          sed -i 's|/home/runner/work/python-project-50/python-project-50/||g' coverage.xml
          sed -i 's|filename="\([^/]*\.py\)"|filename="gendiff/\1"|g' coverage.xml
          echo "Fixed paths:"
          grep "filename=" coverage.xml | head -5

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=dimondimasik
            -Dsonar.projectKey=DimonDimasik_python-project-50
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=.
            -Dsonar.tests=tests
            -Dsonar.python.version=3.10
            -Dsonar.exclusions=**/tests/**,**/__pycache__/**,**/.venv/**
            -Dsonar.coverage.exclusions=**/tests/**,**/__pycache__/**
