name: CI with SonarCloud

on:
  - push
  - pull_request

jobs:
  test:
    name: Test and Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup UV
        uses: astral-sh/setup-uv@v2
        with:
          python-version: '3.10'
          enable-cache: true

      - name: Install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e . pytest pytest-cov coverage

      - name: Run tests with clean coverage
        run: |
          source .venv/bin/activate
          cd $GITHUB_WORKSPACE
          python -m coverage run --source=gendiff -m pytest tests/
          python -m coverage xml

      - name: Remove all path prefixes
        run: |
          echo "Removing all path prefixes from coverage.xml..."
          sed -i 's|python-project-50/||g' coverage.xml
          sed -i 's|/.*/python-project-50/||g' coverage.xml
          sed -i 's|/home/.*/||g' coverage.xml
          sed -i 's|/github/.*/||g' coverage.xml
          sed -i 's|filename="/.*"|filename="gendiff/"|g' coverage.xml
          
          echo "Final paths:"
          grep "filename=" coverage.xml | head -3

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=dimondimasik
            -Dsonar.projectKey=DimonDimasik_python-project-50
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=gendiff
            -Dsonar.tests=tests
            -Dsonar.python.version=3.10
            -Dsonar.exclusions=**/tests/**,**/__pycache__/**,**/.venv/**
